In [2]:
# Import library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Setup pandas
pd.set_option('display.max_columns', None)

# Get the current working directory
os.getcwd()

'/Users/ahmadyusufalbadri/Documents/1 - Learning/4 - Competition/datavidia 2025/Datavidia'

# EDA

The goal of this EDA are:

1. To find relationship between agri-food factors to the global warming from the training data.
2. Find possible feature imputation and engineering for the machine learning model.

## Initial Data Formatting

In [8]:
# Get the data
df_lat_lon_country = pd.read_csv('data/lat_lon_data_pul2.csv')
df_lat_lon_country = df_lat_lon_country.iloc[:, 1:]

df_train = pd.read_csv('data/train.csv')
df_train[['Negara', 'Tahun']] = df_train['Negara/Tahun'].str.split('/', expand=True)
df_train = df_train.iloc[:, 2:]
df_train = df_train.merge(df_lat_lon_country, how='left', left_on='Negara', right_on='country')
df_train.drop('country', axis=1, inplace=True)
df_train.head()

,Emisi Savanna Api,Emisi Kebakaran Hutan,Emisi Residu Tanaman,Emisi Budidaya Padi,Emisi Tanah Organik Yang Dikeringkan (Co2),Emisi Pembuatan Pestisida,Emisi Transportasi Makanan,Lahan Hutan,Konversi Hutan Bersih,Emisi Konsumsi Rumah Tangga Makanan,Emisi Ritel Makanan,Emisi Penggunaan Listrik Di Pertanian,Emisi Kemasan Makanan,Emisi Sistem Agrifood Pembuangan Limbah,Emisi Pengolahan Makanan,Emisi Manufaktur Pupuk,Emisi IPPU,Emisi Kotoran Diterapkan Pada Tanah,Emisi Pupuk Kandang Di Padang Rumput,Emisi Manajemen Pupuk,Emisi Kebakaran Di Tanah Organik,Emisi Kebakaran Di Hutan Tropis Yang Lembab,Penggunaan Energi Di Pertanian,Populasi Pedesaan,Populasi Perkotaan,Total Populasi - Pria,Total Populasi - Wanita,Emisi Total,Peningkatan Suhu Rata - Rata ° C,Negara,Tahun,lat,lon
0,14.7237,0.0557,205.6077,686.00,0.0,11.807483,63.1152,-2388.803,0.0,79.0851,109.6446,14.2666,67.631366,691.7888,252.21419,11.9970,209.9778,260.1431,1590.5319,319.1763,0.0,0.0,NaN,9655167.0,2593947.0,5348387.0,5346409.0,2198.963539,0.536167,Afghanistan,1990,33.768006,66.238514
1,14.7237,0.0557,209.4971,678.16,0.0,11.712073,61.2125,-2388.803,0.0,80.4885,116.6789,11.4182,67.631366,710.8212,252.21419,12.8539,217.0388,268.6292,1657.2364,342.3079,0.0,0.0,NaN,10230490.0,2763167.0,5372959.0,5372208.0,2323.876629,0.020667,Afghanistan,1991,33.768006,66.238514
2,14.7237,0.0557,196.5341,686.00,0.0,11.712073,53.3170,-2388.803,0.0,80.7692,126.1721,9.2752,67.631366,743.6751,252.21419,13.4929,222.1156,264.7898,1653.5068,349.1224,0.0,0.0,NaN,10995568.0,2985663.0,6028494.0,6028939.0,2356.304229,-0.259583,Afghanistan,1992,33.768006,66.238514
3,14.7237,0.0557,230.8175,686.00,0.0,11.712073,54.3617,-2388.803,0.0,85.0678,81.4607,9.0635,67.631366,791.9246,252.21419,14.0559,201.2057,261.7221,1642.9623,352.2947,0.0,0.0,NaN,11858090.0,3237009.0,7003641.0,7000119.0,2368.470529,0.101917,Afghanistan,1993,33.768006,66.238514
4,14.7237,0.0557,242.0494,705.60,0.0,11.712073,53.9874,-2388.803,0.0,88.8058,90.4008,8.3962,67.631366,831.9181,252.21419,15.1269,182.2905,267.6219,1689.3593,367.6784,0.0,0.0,NaN,12690115.0,3482604.0,7733458.0,7722096.0,2500.768729,0.372250,Afghanistan,1994,33.768006,66.238514

In [16]:
# Repositioned the data
temp = df_train.columns.to_list()[-4:] + [df_train.columns.to_list()[-5]] + df_train.columns.to_list()[:-5]
df_train = df_train[temp]
df_train.head()

,Negara,Tahun,lat,lon,Peningkatan Suhu Rata - Rata ° C,Emisi Savanna Api,Emisi Kebakaran Hutan,Emisi Residu Tanaman,Emisi Budidaya Padi,Emisi Tanah Organik Yang Dikeringkan (Co2),Emisi Pembuatan Pestisida,Emisi Transportasi Makanan,Lahan Hutan,Konversi Hutan Bersih,Emisi Konsumsi Rumah Tangga Makanan,Emisi Ritel Makanan,Emisi Penggunaan Listrik Di Pertanian,Emisi Kemasan Makanan,Emisi Sistem Agrifood Pembuangan Limbah,Emisi Pengolahan Makanan,Emisi Manufaktur Pupuk,Emisi IPPU,Emisi Kotoran Diterapkan Pada Tanah,Emisi Pupuk Kandang Di Padang Rumput,Emisi Manajemen Pupuk,Emisi Kebakaran Di Tanah Organik,Emisi Kebakaran Di Hutan Tropis Yang Lembab,Penggunaan Energi Di Pertanian,Populasi Pedesaan,Populasi Perkotaan,Total Populasi - Pria,Total Populasi - Wanita,Emisi Total
0,Afghanistan,1990,33.768006,66.238514,0.536167,14.7237,0.0557,205.6077,686.00,0.0,11.807483,63.1152,-2388.803,0.0,79.0851,109.6446,14.2666,67.631366,691.7888,252.21419,11.9970,209.9778,260.1431,1590.5319,319.1763,0.0,0.0,NaN,9655167.0,2593947.0,5348387.0,5346409.0,2198.963539
1,Afghanistan,1991,33.768006,66.238514,0.020667,14.7237,0.0557,209.4971,678.16,0.0,11.712073,61.2125,-2388.803,0.0,80.4885,116.6789,11.4182,67.631366,710.8212,252.21419,12.8539,217.0388,268.6292,1657.2364,342.3079,0.0,0.0,NaN,10230490.0,2763167.0,5372959.0,5372208.0,2323.876629
2,Afghanistan,1992,33.768006,66.238514,-0.259583,14.7237,0.0557,196.5341,686.00,0.0,11.712073,53.3170,-2388.803,0.0,80.7692,126.1721,9.2752,67.631366,743.6751,252.21419,13.4929,222.1156,264.7898,1653.5068,349.1224,0.0,0.0,NaN,10995568.0,2985663.0,6028494.0,6028939.0,2356.304229
3,Afghanistan,1993,33.768006,66.238514,0.101917,14.7237,0.0557,230.8175,686.00,0.0,11.712073,54.3617,-2388.803,0.0,85.0678,81.4607,9.0635,67.631366,791.9246,252.21419,14.0559,201.2057,261.7221,1642.9623,352.2947,0.0,0.0,NaN,11858090.0,3237009.0,7003641.0,7000119.0,2368.470529
4,Afghanistan,1994,33.768006,66.238514,0.372250,14.7237,0.0557,242.0494,705.60,0.0,11.712073,53.9874,-2388.803,0.0,88.8058,90.4008,8.3962,67.631366,831.9181,252.21419,15.1269,182.2905,267.6219,1689.3593,367.6784,0.0,0.0,NaN,12690115.0,3482604.0,7733458.0,7722096.0,2500.768729

## Analysis

In [17]:
# Check data information
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5603 entries, 0 to 5602
Data columns (total 33 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Negara                                       5603 non-null   object
 1   Tahun                                        5603 non-null   object
 2   lat                                          5603 non-null   float64
 3   lon                                          5603 non-null   float64
 4   Peningkatan Suhu Rata - Rata ° C             5603 non-null   float64
 5   Emisi Savanna Api                            5578 non-null   float64
 6   Emisi Kebakaran Hutan                        5528 non-null   float64
 7   Emisi Residu Tanaman                         4485 non-null   float64
 8   Emisi Budidaya Padi                          5603 non-null   float64
 9   Emisi Tanah Organik Yang Dikeringkan (Co2)   5603 non-null   float64
 10  Emisi Pembuatan Pestisida                    5603 non-null   float64
 11  Emisi Transportasi Makanan                   5603 non-null   float64
 12  Lahan Hutan                                  5206 non-null   float64
 13  Konversi Hutan Bersih                        5206 non-null   float64
 14  Emisi Konsumsi Rumah Tangga Makanan          5214 non-null   float64
 15  Emisi Ritel Makanan                          5603 non-null   float64
 16  Emisi Penggunaan Listrik Di Pertanian        5603 non-null   float64
 17  Emisi Kemasan Makanan                        5603 non-null   float64
 18  Emisi Sistem Agrifood Pembuangan Limbah      5603 non-null   float64
 19  Emisi Pengolahan Makanan                     5603 non-null   float64
 20  Emisi Manufaktur Pupuk                       5603 non-null   float64
 21  Emisi IPPU                                   5004 non-null   float64
 22  Emisi Kotoran Diterapkan Pada Tanah          4851 non-null   float64
 23  Emisi Pupuk Kandang Di Padang Rumput         5603 non-null   float64
 24  Emisi Manajemen Pupuk                        4851 non-null   float64
 25  Emisi Kebakaran Di Tanah Organik             5603 non-null   float64
 26  Emisi Kebakaran Di Hutan Tropis Yang Lembab  5478 non-null   float64
 27  Penggunaan Energi Di Pertanian               4821 non-null   float64
 28  Populasi Pedesaan                            5603 non-null   float64
 29  Populasi Perkotaan                           5603 non-null   float64
 30  Total Populasi - Pria                        5603 non-null   float64
 31  Total Populasi - Wanita                      5603 non-null   float64
 32  Emisi Total                                  5603 non-null   float64
dtypes: float64(31), object(2)
memory usage: 1.4+ MB

In [21]:
# Check missing values and duplicates
print('====================================\nMISSING VALUES CHECK:\n====================================')
print(df_train.isna().sum().sort_values(ascending=False))
print()
print('====================================\nDATA DUPLICATE CHECK:', df_train.duplicated().sum(), '\n====================================')

====================================
MISSING VALUES CHECK:
====================================
Emisi Residu Tanaman                           1118
Penggunaan Energi Di Pertanian                  782
Emisi Kotoran Diterapkan Pada Tanah             752
Emisi Manajemen Pupuk                           752
Emisi IPPU                                      599
Lahan Hutan                                     397
Konversi Hutan Bersih                           397
Emisi Konsumsi Rumah Tangga Makanan             389
Emisi Kebakaran Di Hutan Tropis Yang Lembab     125
Emisi Kebakaran Hutan                            75
Emisi Savanna Api                                25
Populasi Perkotaan                                0
Populasi Pedesaan                                 0
Emisi Manufaktur Pupuk                            0
Emisi Kebakaran Di Tanah Organik                  0
Total Populasi - Pria                             0
Emisi Pupuk Kandang Di Padang Rumput              0
Total Populasi - Wanita                           0
Negara                                            0
Emisi Penggunaan Listrik Di Pertanian             0
Emisi Pengolahan Makanan                          0
Emisi Sistem Agrifood Pembuangan Limbah           0
Emisi Kemasan Makanan                             0
Tahun                                             0
Emisi Ritel Makanan                               0
Emisi Transportasi Makanan                        0
Emisi Pembuatan Pestisida                         0
Emisi Tanah Organik Yang Dikeringkan (Co2)        0
Emisi Budidaya Padi                               0
Peningkatan Suhu Rata - Rata ° C                  0
lon                                               0
lat                                               0
Emisi Total                                       0
dtype: int64

====================================
DATA DUPLICATE CHECK: 0
====================================

In [22]:
# Convert tahun to int
df_train['Tahun'] = df_train['Tahun'].astype(int)

In [24]:
# Describe the data
df_train.describe().astype(str)

,Tahun,lat,lon,Peningkatan Suhu Rata - Rata ° C,Emisi Savanna Api,Emisi Kebakaran Hutan,Emisi Residu Tanaman,Emisi Budidaya Padi,Emisi Tanah Organik Yang Dikeringkan (Co2),Emisi Pembuatan Pestisida,Emisi Transportasi Makanan,Lahan Hutan,Konversi Hutan Bersih,Emisi Konsumsi Rumah Tangga Makanan,Emisi Ritel Makanan,Emisi Penggunaan Listrik Di Pertanian,Emisi Kemasan Makanan,Emisi Sistem Agrifood Pembuangan Limbah,Emisi Pengolahan Makanan,Emisi Manufaktur Pupuk,Emisi IPPU,Emisi Kotoran Diterapkan Pada Tanah,Emisi Pupuk Kandang Di Padang Rumput,Emisi Manajemen Pupuk,Emisi Kebakaran Di Tanah Organik,Emisi Kebakaran Di Hutan Tropis Yang Lembab,Penggunaan Energi Di Pertanian,Populasi Pedesaan,Populasi Perkotaan,Total Populasi - Pria,Total Populasi - Wanita,Emisi Total
count,5603.0,5603.0,5603.0,5603.0,5578.0,5528.0,4485.0,5603.0,5603.0,5603.0,5603.0,5206.0,5206.0,5214.0,5603.0,5603.0,5603.0,5603.0,5603.0,5603.0,5004.0,4851.0,5603.0,4851.0,5603.0,5478.0,4821.0,5603.0,5603.0,5603.0,5603.0,5603.0
mean,2002.1167231840086,17.642178043899094,9.308831156629843,0.7501702568951026,1229.6544452491933,924.2751989146165,949.2050756075809,4241.101703878332,3471.7915703908625,327.5222891339001,1823.1383028019652,-18145.65406171725,18454.522389684982,4290.229335558112,1726.5583187622726,1524.6925477490424,1547.357603083276,5919.614031722235,3779.3597751397306,2900.800427282518,17309.192334972024,913.2562305916307,3431.750042752865,2252.8005198309625,1254.336085041337,668.2839432822198,3015.8050467537855,17949028.825629126,15738814.348384794,17038810.178604193,16756698.563587843,60571.36914473102
std,7.166376713604766,24.178537713251004,76.06667760094686,0.4989433758492056,5472.353827553386,3692.5848811941282,3498.477163822186,17599.627762521446,15488.661938100191,1445.4848650654835,5306.417931085816,81045.73582102315,108004.96140860341,20691.80766340678,6882.576637017679,8356.445934711754,10235.123944206767,21758.44409807351,19356.823253121755,11016.456584276986,91075.90974998647,3215.0607254423044,8926.859188341768,8010.868244206085,23189.667834312146,3243.015188127321,12391.323705683406,90736574.0355425,59203131.67387243,73982191.22445323,70561958.84090337,208490.41680261333
min,1990.0,-51.9492937,-176.204224,-1.4158333333333335,0.0,0.0,0.0002,0.0,0.0,0.0,0.0001,-797183.079,0.0,0.0,0.0,0.0,0.0,0.34,0.0001,0.0019,0.0,0.049,0.0007,0.4329,0.0,0.0,0.0319,0.0,0.0,270.0,300.0,-391884.0563
25%,1996.0,1.613172,-60.9620777,0.44033333333333335,0.0,0.0,10.9211,172.2193,0.0,5.0,26.262663446183105,-3224.3715,0.0,10.011225,20.42625,7.2017500000000005,67.63136607385836,85.68311232412132,209.58772835754152,356.4910168671663,34.17885,15.263200000000001,142.52530000000002,36.8658,0.0,0.0,12.1815,94314.0,204572.0,194837.0,200354.5,5135.02952071779
50%,2002.0,16.7417041,14.12456,0.72975,1.6579,0.66185,98.0374,515.5172,0.0,12.328280513854102,176.0653,-69.5346,44.616,136.2674,141.7096,27.636841710447985,71.28785384639453,868.0077,332.6036474920459,1093.665,707.7274,113.5816,964.8423,255.4619,0.0,0.0,134.4775,1572038.0,2201558.0,2336340.0,2338950.0,11748.019463854458
75%,2008.0,38.6281733,47.9734174,1.0301666666666667,114.3092,71.0949,356.2161,1551.41055,694.1645000000001,106.9817314214948,1135.64975,0.0,4734.96775,1357.8258999999998,905.57545,492.7371464768823,267.07297555428045,2945.4187,1108.6982,2012.447178005524,5675.145625,454.5236,2319.68205,1121.8815,0.0,10.189775,1151.3962,7836860.5,7690343.0,8586905.5,8617357.5,32921.11201448267
max,2014.0,64.9841821,179.1582918181797,3.143,114616.4011,52227.6306,30638.5338,164915.2556,232118.4694,16459.0,62048.1673,171121.076,1605106.096,344626.3392,104356.5616,141904.3336,175741.3061,213289.7016,274253.5125,170826.4233,1619276.0171,34677.3603,88494.2199,70592.6465,991717.5431,51771.2568,248879.1769,874857621.0,779954516.0,724363944.0,692204586.0,2741629.5747

In [39]:
# Check countries with null
temp = df_train.isna().sum().sort_values(ascending=False)
temp2 = df_train['Negara'].value_counts(dropna=False).reset_index()
for i in temp[temp > 0].index:
    print(f'NULL VALUES FOR __{i}__ AS FOLLOW:')
    print(df_train[df_train[i].isna()]['Negara'].value_counts(dropna=False).reset_index().merge(temp2, how='left', on='Negara'))
    print()

NULL VALUES FOR __Emisi Residu Tanaman__ AS FOLLOW:
                                          Negara  count_x  count_y
0                                 American Samoa       25       25
1                                  Liechtenstein       25       25
2                                        Mayotte       25       25
3                                         Monaco       25       25
4                                          Nauru       25       25
5                                           Niue       25       25
6   Saint Helena, Ascension and Tristan da Cunha       25       25
7                                    Saint Lucia       25       25
8                      Saint Pierre and Miquelon       25       25
9                                          Samoa       25       25
10                                    San Marino       25       25
11                                    Seychelles       25       25
12                                     Singapore       25       25
13                                       Tokelau       25       25
14                                         Tonga       25       25
15                      Turks and Caicos Islands       25       25
16                                        Tuvalu       25       25
17                  United States Virgin Islands       25       25
18                     Wallis and Futuna Islands       25       25
19                                       Andorra       25       25
20                                    Martinique       25       25
21                                      Kiribati       25       25
22                                     Gibraltar       25       25
23                                      Anguilla       25       25
24                                         Aruba       25       25
25                        British Virgin Islands       25       25
26                                Cayman Islands       25       25
27                               Channel Islands       25       25
28                              China, Macao SAR       25       25
29                                  Cook Islands       25       25
30                             Equatorial Guinea       25       25
31                   Falkland Islands (Malvinas)       25       25
32                                     Greenland       25       25
33                                    Guadeloupe       25       25
34                                      Holy See       25       25
35                                   Isle of Man       25       25
36                                         Palau       24       24
37                              Marshall Islands       24       24
38                      Northern Mariana Islands       24       24
39                          China, Hong Kong SAR       24       25
40                                    Montserrat       24       25
41                                          Guam       24       25
42                                       Bermuda       24       25
43                                Western Sahara       24       25
44                 Netherlands Antilles (former)       21       21
45                                     Palestine        4       25
46                                       Bahrain        1       25

NULL VALUES FOR __Penggunaan Energi Di Pertanian__ AS FOLLOW:
                              Negara  count_x  count_y
0                        Afghanistan       25       25
1                       Saudi Arabia       25       25
2                        Puerto Rico       25       25
3                           Paraguay       25       25
4                          Singapore       25       25
5                               Oman       25       25
6                              Niger       25       25
7                               Togo       25       25
8                             Monaco       25       25
9                            Bahrain       25       25
10                           Tokelau       25       25
11                        Madagascar       25       25
12                             Libya       25       25
13                           Lesotho       25       25
14                            Kuwait       25       25
15                        San Marino       25       25
16                              Iraq       25       25
17  Democratic Republic of the Congo       25       25
18                      Burkina Faso       25       25
19                          Cameroon       25       25
20                   Channel Islands       25       25
21              China, Hong Kong SAR       25       25
22                          Holy See       25       25
23                    Western Sahara       25       25
24      United States Virgin Islands       25       25
25              United Arab Emirates       25       25
26                              Fiji       25       25
27                              Guam       25       25
28                      Turkmenistan       23       23
29             Serbia and Montenegro       14       14
30                       Timor-Leste       12       25
31                       Isle of Man       12       25
32                Belgium-Luxembourg       10       10
33  Micronesia (Federated States of)        1       24
34                             Palau        1       24
35   Pacific Islands Trust Territory        1        1
36          Northern Mariana Islands        1       24
37                           Namibia        1       25
38                  Marshall Islands        1       24
39                           Germany        1       25
40                          Ethiopia        1       22
41                           Eritrea        1       22
42                    Czechoslovakia        1        3
43                             Yemen        1       25

NULL VALUES FOR __Emisi Kotoran Diterapkan Pada Tanah__ AS FOLLOW:
                                          Negara  count_x  count_y
0                                 American Samoa       25       25
1                                  Liechtenstein       25       25
2                      Wallis and Futuna Islands       25       25
3                   United States Virgin Islands       25       25
4                       Turks and Caicos Islands       25       25
5                                     San Marino       25       25
6                      Saint Pierre and Miquelon       25       25
7   Saint Helena, Ascension and Tristan da Cunha       25       25
8                                     Montserrat       25       25
9                                         Monaco       25       25
10                                       Mayotte       25       25
11                                       Andorra       25       25
12                                      Maldives       25       25
13                                Western Sahara       25       25
14                                   Isle of Man       25       25
15                               Channel Islands       25       25
16                                          Guam       25       25
17                                     Greenland       25       25
18                                      Anguilla       25       25
19                                     Gibraltar       25       25
20                   Falkland Islands (Malvinas)       25       25
21                                         Aruba       25       25
22                                       Bermuda       25       25
23                                      Holy See       25       25
24                        British Virgin Islands       25       25
25                                Cayman Islands       25       25
26                              Marshall Islands       24       24
27                                         Palau       24       24
28                      Northern Mariana Islands       24       24
29                 Netherlands Antilles (former)       21       21
30                                     Palestine        4       25
31              Micronesia (Federated States of)        4       24
32               Pacific Islands Trust Territory        1        1

NULL VALUES FOR __Emisi Manajemen Pupuk__ AS FOLLOW:
                                          Negara  count_x  count_y
0                                 American Samoa       25       25
1                                  Liechtenstein       25       25
2                      Wallis and Futuna Islands       25       25
3                   United States Virgin Islands       25       25
4                       Turks and Caicos Islands       25       25
5                                     San Marino       25       25
6                      Saint Pierre and Miquelon       25       25
7   Saint Helena, Ascension and Tristan da Cunha       25       25
8                                     Montserrat       25       25
9                                         Monaco       25       25
10                                       Mayotte       25       25
11                                       Andorra       25       25
12                                      Maldives       25       25
13                                Western Sahara       25       25
14                                   Isle of Man       25       25
15                               Channel Islands       25       25
16                                          Guam       25       25
17                                     Greenland       25       25
18                                      Anguilla       25       25
19                                     Gibraltar       25       25
20                   Falkland Islands (Malvinas)       25       25
21                                         Aruba       25       25
22                                       Bermuda       25       25
23                                      Holy See       25       25
24                        British Virgin Islands       25       25
25                                Cayman Islands       25       25
26                              Marshall Islands       24       24
27                                         Palau       24       24
28                      Northern Mariana Islands       24       24
29                 Netherlands Antilles (former)       21       21
30                                     Palestine        4       25
31              Micronesia (Federated States of)        4       24
32               Pacific Islands Trust Territory        1        1

NULL VALUES FOR __Emisi IPPU__ AS FOLLOW:
                          Negara  count_x  count_y
0                 American Samoa       25       25
1                        Bermuda       25       25
2      Wallis and Futuna Islands       25       25
3   United States Virgin Islands       25       25
4                        Tokelau       25       25
5      Saint Pierre and Miquelon       25       25
6                    Puerto Rico       25       25
7                      Palestine       25       25
8                  New Caledonia       25       25
9                     Montserrat       25       25
10                       Mayotte       25       25
11                    Martinique       25       25
12                   Isle of Man       25       25
13                          Guam       25       25
14                    Guadeloupe       25       25
15                     Greenland       25       25
16                     Gibraltar       25       25
17              French Polynesia       25       25
18                 Faroe Islands       25       25
19   Falkland Islands (Malvinas)       25       25
20               Channel Islands       25       25
21                Cayman Islands       25       25
22                Western Sahara       25       25
23      Northern Mariana Islands       24       24

NULL VALUES FOR __Lahan Hutan__ AS FOLLOW:
                       Negara  count_x  count_y
0                    Anguilla       25       25
1         Antigua and Barbuda       25       25
2                     Bermuda       25       25
3      British Virgin Islands       25       25
4             Channel Islands       25       25
5        China, Hong Kong SAR       25       25
6            China, Macao SAR       25       25
7   China, Taiwan Province of       25       25
8                 Isle of Man       25       25
9                    Kiribati       25       25
10                  Palestine       25       25
11      Saint Kitts and Nevis       25       25
12       United Arab Emirates       25       25
13                    Vanuatu       25       25
14                      Palau       24       24
15            North Macedonia       23       23

NULL VALUES FOR __Konversi Hutan Bersih__ AS FOLLOW:
                       Negara  count_x  count_y
0                    Anguilla       25       25
1         Antigua and Barbuda       25       25
2                     Bermuda       25       25
3      British Virgin Islands       25       25
4             Channel Islands       25       25
5        China, Hong Kong SAR       25       25
6            China, Macao SAR       25       25
7   China, Taiwan Province of       25       25
8                 Isle of Man       25       25
9                    Kiribati       25       25
10                  Palestine       25       25
11      Saint Kitts and Nevis       25       25
12       United Arab Emirates       25       25
13                    Vanuatu       25       25
14                      Palau       24       24
15            North Macedonia       23       23

NULL VALUES FOR __Emisi Konsumsi Rumah Tangga Makanan__ AS FOLLOW:
                                          Negara  count_x  count_y
0                                        Namibia       25       25
1                                     Martinique       25       25
2                      Wallis and Futuna Islands       25       25
3                   United States Virgin Islands       25       25
4                                        Tokelau       25       25
5                      Saint Pierre and Miquelon       25       25
6   Saint Helena, Ascension and Tristan da Cunha       25       25
7                         British Virgin Islands       25       25
8                                 Western Sahara       25       25
9                                         Gambia       25       25
10                                       Liberia       25       25
11                               Channel Islands       25       25
12                                  Cook Islands       25       25
13                                          Guam       25       25
14                            Belgium-Luxembourg       10       10
15                                    Montserrat        9       25
16                         Serbia and Montenegro        6       14
17                   Falkland Islands (Malvinas)        3       25
18                                   Timor-Leste        3       25
19                                       Somalia        2       25
20               Pacific Islands Trust Territory        1        1
21                                         Palau        1       24
22                      Northern Mariana Islands        1       24
23                                  Ethiopia PDR        1        3
24              Micronesia (Federated States of)        1       24
25                              Marshall Islands        1       24

NULL VALUES FOR __Emisi Kebakaran Di Hutan Tropis Yang Lembab__ AS FOLLOW:
            Negara  count_x  count_y
0  Channel Islands       25       25
1         Holy See       25       25
2    Liechtenstein       25       25
3           Monaco       25       25
4       San Marino       25       25

NULL VALUES FOR __Emisi Kebakaran Hutan__ AS FOLLOW:
       Negara  count_x  count_y
0    Holy See       25       25
1      Monaco       25       25
2  San Marino       25       25

NULL VALUES FOR __Emisi Savanna Api__ AS FOLLOW:
     Negara  count_x  count_y
0  Holy See       25       25

In [40]:
# Check a sample of Bahrain
df_train[df_train['Negara'] == 'Bahrain']

,Negara,Tahun,lat,lon,Peningkatan Suhu Rata - Rata ° C,Emisi Savanna Api,Emisi Kebakaran Hutan,Emisi Residu Tanaman,Emisi Budidaya Padi,Emisi Tanah Organik Yang Dikeringkan (Co2),Emisi Pembuatan Pestisida,Emisi Transportasi Makanan,Lahan Hutan,Konversi Hutan Bersih,Emisi Konsumsi Rumah Tangga Makanan,Emisi Ritel Makanan,Emisi Penggunaan Listrik Di Pertanian,Emisi Kemasan Makanan,Emisi Sistem Agrifood Pembuangan Limbah,Emisi Pengolahan Makanan,Emisi Manufaktur Pupuk,Emisi IPPU,Emisi Kotoran Diterapkan Pada Tanah,Emisi Pupuk Kandang Di Padang Rumput,Emisi Manajemen Pupuk,Emisi Kebakaran Di Tanah Organik,Emisi Kebakaran Di Hutan Tropis Yang Lembab,Penggunaan Energi Di Pertanian,Populasi Pedesaan,Populasi Perkotaan,Total Populasi - Pria,Total Populasi - Wanita,Emisi Total
371,Bahrain,1990,26.030093,50.553337,0.652750,0.0,0.0,0.0006,246.407276,0.0,0.0,116.0378,-1.8626,0.0,181.3300,154.9085,21.1401,625.5804,320.7606,247.314516,70.4939,4237.9918,0.6294,12.2198,1.5460,0.0,0.0,NaN,58816.0,437115.0,302861.0,214558.0,6234.498093
372,Bahrain,1991,26.030093,50.553337,-0.267417,0.0,0.0,0.0006,246.407276,0.0,1.0,117.1316,-1.8626,0.0,176.0500,138.9684,12.8610,601.4023,331.0686,209.587728,86.6473,1731.5459,0.6363,11.9063,1.5451,0.0,0.0,NaN,59494.0,450271.0,313375.0,222040.0,3664.895805
373,Bahrain,1992,26.030093,50.553337,-0.679583,0.0,0.0,0.0010,246.407276,0.0,0.0,129.9014,-1.8626,0.0,206.0455,144.2447,17.3818,620.8618,340.3253,209.587728,101.1022,1944.8331,0.6505,12.0762,1.5533,0.0,0.0,NaN,60688.0,462399.0,324822.0,229648.0,3973.109205
374,Bahrain,1993,26.030093,50.553337,0.239417,0.0,0.0,0.0013,246.407276,0.0,0.0,125.2621,-1.8626,0.0,205.0604,118.9537,18.1512,758.5181,348.4510,209.587728,114.5978,2337.2729,0.6608,11.8851,1.5549,0.0,0.0,NaN,62228.0,473985.0,336425.0,237331.0,4494.501705
375,Bahrain,1994,26.030093,50.553337,0.822167,0.0,0.0,0.0015,246.407276,0.0,0.0,132.0274,-1.8626,0.0,230.1559,149.0632,21.7109,757.7321,355.8552,209.587728,132.1606,2112.1978,0.6677,11.5924,1.5412,0.0,0.0,NaN,63798.0,485790.0,348166.0,245088.0,4358.838305
376,Bahrain,1995,26.030093,50.553337,0.282750,0.0,0.0,0.0006,246.407276,0.0,0.0,134.1660,-1.8626,0.0,242.7003,175.2565,22.2992,797.3384,362.3908,209.587728,147.2936,2147.4887,0.6624,10.9094,1.4645,0.0,0.0,NaN,65454.0,498245.0,360022.0,252912.0,4496.102805
377,Bahrain,1996,26.030093,50.553337,0.854667,0.0,0.0,0.0003,246.407276,0.0,0.0,142.3140,-1.8626,0.0,255.8283,160.2765,23.0986,828.7693,372.6832,209.587728,164.8404,2055.0058,0.6836,11.6595,1.5715,0.0,0.0,NaN,67211.0,511457.0,371964.0,260792.0,4470.863405
378,Bahrain,1997,26.030093,50.553337,0.310583,0.0,0.0,0.0002,246.407276,0.0,0.0,149.4938,-1.8626,0.0,256.3521,187.5107,24.3320,549.2585,382.2813,209.587728,183.6778,2255.8428,0.7010,11.7978,1.5941,0.0,0.0,NaN,69119.0,525811.0,383949.0,268694.0,4456.974505
379,Bahrain,1998,26.030093,50.553337,1.682667,0.0,0.0,0.0002,246.407276,0.0,0.0,157.7614,-1.8626,0.0,286.0472,223.2288,30.4988,191.0169,391.2334,209.587728,201.8677,2194.0055,0.5460,11.3571,1.4136,0.0,0.0,NaN,71319.0,542383.0,395916.0,276567.0,4143.109005
380,Bahrain,1999,26.030093,50.553337,1.823333,0.0,0.0,0.0002,246.407276,0.0,0.0,163.9440,-1.8626,0.0,302.5149,269.1444,28.5776,236.7943,400.0025,209.587728,222.0003,2242.1034,0.5443,11.8070,1.4711,0.0,0.0,NaN,73994.0,562551.0,407807.0,284326.0,4333.036405
381,Bahrain,2000,26.030093,50.553337,1.121750,0.0,0.0,0.0005,246.407276,0.0,1.0,173.7724,-1.8626,0.0,304.8988,363.6092,27.9072,295.0760,409.3681,209.587728,238.0716,2096.5623,0.5375,11.4429,1.4676,0.0,0.0,NaN,77278.0,587336.0,419570.0,291872.0,4377.846505
382,Bahrain,2001,26.030093,50.553337,1.501000,0.0,0.0,0.0002,246.407276,0.0,0.0,175.8902,-2.2711,0.0,322.2744,440.9946,27.5298,393.1904,417.4480,209.587728,256.1016,2200.2229,0.5012,10.9385,1.3891,0.0,0.0,NaN,81130.0,616419.0,431149.0,299108.0,4700.204805
383,Bahrain,2002,26.030093,50.553337,1.290250,0.0,0.0,0.0002,246.407276,0.0,0.0,205.4948,-2.2711,0.0,344.2861,434.5492,29.2356,466.5985,425.2697,1.287500,411.3599,2141.6113,0.5600,14.1540,1.7105,0.0,0.0,NaN,85478.0,649670.0,442442.0,305882.0,4720.253476
384,Bahrain,2003,26.030093,50.553337,1.255583,0.0,0.0,0.0002,246.407276,0.0,0.0,223.6744,-2.2711,0.0,371.7224,463.2727,28.2030,512.7725,432.7098,1.339100,375.1674,2019.2968,0.5217,12.6188,1.5353,0.0,0.0,NaN,90466.0,688245.0,462113.0,316143.0,4686.970276
385,Bahrain,2004,26.030093,50.553337,1.212500,0.0,0.0,0.0004,246.407276,0.0,0.0,247.0502,-2.2711,0.0,374.0800,466.7343,29.0636,549.0844,440.2591,1.358300,326.9481,2161.4168,0.5023,11.9401,1.4439,0.0,0.0,NaN,96270.0,733578.0,499158.0,334293.0,4854.017676
386,Bahrain,2005,26.030093,50.553337,1.322000,0.0,0.0,NaN,757.756643,0.0,0.0,290.5864,-2.2711,0.0,401.7499,562.2530,31.7177,623.0480,448.4426,1.890800,357.9035,2673.5787,0.4890,11.7991,1.4086,0.0,0.0,NaN,102947.0,786221.0,545191.0,356731.0,6160.352843
387,Bahrain,2006,26.030093,50.553337,1.422917,0.0,0.0,0.0002,246.407276,0.0,0.0,302.0116,-2.2711,0.0,475.4310,553.2983,34.1593,806.1853,456.2406,2.519900,412.1317,3028.7480,0.5119,11.9479,1.4218,0.0,0.0,NaN,110681.0,847733.0,591506.0,379474.0,6328.743676
388,Bahrain,2007,26.030093,50.553337,1.346500,0.0,0.0,0.0002,246.407276,0.0,1.0,328.9103,-2.2711,0.0,468.6268,578.3833,32.5598,614.2028,464.5135,2.978600,371.2538,2946.7167,0.5178,11.8274,1.4160,0.0,0.0,NaN,119256.0,916635.0,638061.0,402471.0,6067.043176
389,Bahrain,2008,26.030093,50.553337,1.204500,0.0,0.0,0.0004,246.407276,0.0,0.0,360.1800,-2.2711,0.0,485.8755,591.4980,32.3610,650.7258,472.7998,3.434900,422.2978,3112.4447,0.5113,10.4020,1.3020,0.0,0.0,NaN,127843.0,986747.0,684764.0,425579.0,6387.969376
390,Bahrain,2009,26.030093,50.553337,1.421750,0.0,0.0,0.0012,246.407276,0.0,0.0,355.7943,-2.2711,0.0,511.1418,616.4302,34.7380,734.2858,479.8473,3.442900,435.9763,3145.3492,0.5182,10.6963,1.3321,0.0,0.0,NaN,135345.0,1049684.0,731120.0,448332.0,6573.689776
391,Bahrain,2010,26.030093,50.553337,2.278750,0.0,0.0,0.0012,246.407276,0.0,0.0,359.9111,-2.2711,0.0,535.6674,713.5754,37.0147,499.9494,486.1659,4.063600,400.8506,3257.6627,0.5558,12.0445,1.4892,0.0,0.0,NaN,141040.0,1099822.0,754000.0,459645.0,6553.087676
392,Bahrain,2011,26.030093,50.553337,1.178333,0.0,0.0,0.0004,246.407276,0.0,0.0,337.7110,-2.8947,0.0,530.5120,678.8750,36.2496,531.3230,491.8871,4.372000,442.4797,3399.5541,0.5630,12.0747,1.4975,0.0,0.0,NaN,144510.0,1133759.0,753809.0,458268.0,6710.611676
393,Bahrain,2012,26.030093,50.553337,1.665833,0.0,0.0,0.0004,246.407276,0.0,0.0,371.4928,-2.8947,0.0,571.1216,687.4287,34.1866,541.6990,496.4587,4.747600,405.2285,3302.4721,0.5701,12.1369,1.5100,0.0,0.0,NaN,146117.0,1154100.0,765423.0,459516.0,6672.565576
394,Bahrain,2013,26.030093,50.553337,1.281750,0.0,0.0,0.0004,246.407276,0.0,0.0,367.3759,-2.8947,0.0,550.9154,750.5441,39.5564,632.9537,500.9895,4.927100,431.9730,3430.1699,0.5773,12.3415,1.5358,0.0,0.0,NaN,146861.0,1168550.0,787263.0,474410.0,6967.372576
395,Bahrain,2014,26.030093,50.553337,1.801167,0.0,0.0,0.0004,246.407276,0.0,0.0,378.6713,-2.8947,0.0,630.0973,775.8163,36.2400,587.2098,504.5994,5.070100,434.1593,3485.1319,0.5708,12.3154,1.5337,0.0,0.0,NaN,148146.0,1188251.0,810704.0,500430.0,7094.928276